import tkinter as tk
import pyttsx3
import nltk
from textblob import TextBlob
from newspaper import Article
def ncm2():
    speech = pyttsx3.init()
    answer = tsum.get('1.0', "end")
    print(answer)
    speech.say(answer)
    speech.runAndWait()
def ncm():
    url = turl.get('1.0', "end").strip()
    article = Article(url)
    article.download()
    article.parse()
    article.nlp()
    ttitle.config(state="normal")
    tauthor.config(state="normal")
    tpub.config(state="normal")
    tsum.config(state="normal")
    tpola.config(state="normal")
    tsen.config(state="normal")
    ttitle.delete('1.0', "end")
    ttitle.insert('1.0', article.title)
    tauthor.delete('1.0', "end")
    if len(article.authors) == 0 :
        tauthor.insert('1.0', "Author's name is not mentioned!!")
    else:
        tauthor.insert('1.0', article.authors)
    tpub.delete('1.0', "end")
    tpub.insert('1.0', article.publish_date)
    tsum.delete('1.0', "end")
    tsum.insert('1.0', article.summary)
    tpola.delete('1.0', "end")
    analysis = TextBlob(article.text)
    tpola.insert('1.0', analysis.polarity)
    if analysis.polarity > 0:
        sentiment = "Positive"
    elif analysis.polarity < 0:
        sentiment = "Negative"
    else:
        sentiment = "Neutral"
    tsen.delete('1.0', "end")
    tsen.insert('1.0', sentiment)
    ttitle.config(state="disable")
    tauthor.config(state="disable")
    tpub.config(state="disable")
    tsum.config(state="disable")
    tpola.config(state="disable")
    tsen.config(state="disable")
    lis = tk.Button(root, text="Listen", command=ncm2)
    lis.config(font=("Arial", 12, "bold"), bg="#f1c40f", fg="Black", height=1, width=8)
    lis.place(x=902, y=518)

root = tk.Tk()
root.geometry("1000x600")
root.title("News Article Summarizer By Nifat Chowdhury Mahin")
root.config(bg="#2c3e50")
lurl = tk.Label(root, text="URL: ")
lurl.config(bg="#2c3e50", fg="Yellow",font=("Arial", 14, "bold"))
lurl.pack(side=tk.LEFT)
lurl.place(x = 10, y = 10)
turl = tk.Text(root)
turl.config(font=("Arial", 12), height=1, width=100)
turl.pack(side=tk.LEFT)
turl.place(x = 85, y = 14)
ltitle = tk.Label(root, text="Title: ")
ltitle.config(bg="#2c3e50", fg="Yellow", font=("Arial", 14, "bold"))
ltitle.pack(side=tk.LEFT)
ltitle.place(x=10, y=85)
ttitle = tk.Text(root)
ttitle.config(font=("Arial", 12), height=1, width=108, state="disable")
ttitle.pack(side=tk.LEFT)
ttitle.place(x = 15, y = 120)
lauthor = tk.Label(root, text="Authors: ")
lauthor.config(bg="#2c3e50", fg="Yellow", font=("Arial", 14, "bold"))
lauthor.pack(side=tk.LEFT)
lauthor.place(x = 10, y = 160)
tauthor = tk.Text(root)
tauthor.config(font=("Arial", 12), height=1, width=108, state="disable")
tauthor.pack(side=tk.LEFT)
tauthor.place(x = 15, y = 190)
lpub = tk.Label(root, text="Publication Date: ")
lpub.config(font=("Arial", 14, "bold"), bg="#2c3e50", fg="Yellow")
lpub.pack(side=tk.LEFT)
lpub.place(x = 10, y = 230)
tpub = tk.Text(root)
tpub.config(font=("Arial", 12), state="disable", height=1, width=108)
tpub.pack(side=tk.LEFT)
tpub.place(x = 15, y = 260)
lsum = tk.Label(root, text="Summary of the Article: ")
lsum.config(font=("Arial", 14, "bold"), bg="#2c3e50", fg="Yellow")
lsum.pack(side=tk.LEFT)
lsum.place(x = 10, y = 300)
tsum = tk.Text(root)
tsum.config(font=("Arial", 12), height=12, width=108, state="disable")
tsum.pack(side=tk.LEFT)
tsum.place(x = 15, y = 330)

lpola = tk.Label(root, text="Polarity: ")
lpola.config(font=("Arial", 14, "bold"), bg="#2c3e50", fg="Yellow")
lpola.pack(side=tk.LEFT)
lpola.place(x = 10, y = 560)
tpola = tk.Text(root)
tpola.config(font=("Arial", 12), height=1, width=25, state="disable")
tpola.pack(side=tk.LEFT)
tpola.place(x = 100, y = 565)
lsen = tk.Label(root, text="Sentiment: ")
lsen.config(font=("Arial", 14, "bold"), bg="#2c3e50", fg="Yellow")
lsen.pack(side=tk.LEFT)
lsen.place(x = 400, y = 562)
tsen = tk.Text(root)
tsen.config(font=("Arial", 12), height=1, width=25, state="disable")
tsen.pack(side=tk.LEFT)
tsen.place(x = 510, y = 565)
sb = tk.Button(root, text="Submit", command=ncm)
sb.config(font=("Arial", 12, "bold"), bg="#f1c40f", fg="Black", height=1, width=8)
sb.place(x = 450,y = 50)
root.mainloop()